config/routes.rb
Rails.application.routes.draw do
  root 'steam_library#index'

  get 'steam_library/show', to: 'steam_library#show', as: 'steam_library_show'
  get 'steam_library/index', to: 'steam_library#index', as: 'steam_library'
  get 'steam_library/error', as: 'steam_library_error'

  # This route must be the last line of the file
  match '*path', to: redirect('/'), via: :all if Rails.env.production?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: games
#
#  id                :integer          not null, primary key
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  name              :string           not null
#  appid             :string           not null
#  tier              :string           not null
#  trending_tier     :string           not null
#
class Game < ApplicationRecord
  enum_tier = { native: 1, platinum: 2, gold: 3, silver: 4, bronze: 5, borked: 6, unknown: 7 }
  enum tier: enum_tier, _default: :unknown, _suffix: true
  enum trending_tier: enum_tier, _default: :unknown, _suffix: true

  validates :appid, uniqueness: { message: I18n.t('games.errors.appid_must_be_unique') }, presence: true
  validates :name, presence: true
  validates :tier, presence: true
  validates :trending_tier, presence: true

  scope :find_by_appids_and_order_by_tier, ->(appids) { where(appid: appids).order(:tier, :trending_tier) }

  NATIVE = 'native'

  def need_to_update?
    native_game_not_updated? || windows_game_not_updated?
  end

  def numeric_tier_value
    self.class.tiers[tier]
  end

  def numeric_trending_tier_value
    self.class.trending_tiers[trending_tier]
  end

  def tier=(value)
    super value || Game.tiers[:unknown]
  rescue StandardError
    super Game.tiers[:unknown]
  end

  def trending_tier=(value)
    super value || Game.trending_tiers[:unknown]
  rescue StandardError
    super Game.trending_tiers[:unknown]
  end

  private

  def native_game_not_updated?
    !windows_game? && (updated_at <= (Date.today - 2.weeks))
  end

  def windows_game_not_updated?
    if tier != trending_tier
      windows_game? && (updated_at <= (Date.today - 2.days))
    else
      windows_game? && (updated_at <= (Date.today - 4.days))
    end
  end

  def windows_game?
    id.present? && updated_at.present? && NATIVE != tier
  end
end

app/models/steam_library.rb
# frozen_string_literal: true

# rubocop:disable Style/Documentation

class SteamLibrary
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Model

  attr_accessor :games, :steam_id, :checklist

  VALID_CHECKLIST = %w[library wishlist].freeze

  validates :steam_id, length: { is: 17 }, numericality: { only_integer: true }
  validates :checklist, inclusion: { in: VALID_CHECKLIST }

  def initialize(values = {})
    @steam_id = values['steam_id']
    @games = values['games'] || []
    @checklist = values['checklist'] || 'library'
  end

  def persisted? = false

  def change_list
    if @checklist.eql?(SteamLibrary.checklist_library)
      SteamLibrary.checklist_wishlist
    else
      SteamLibrary.checklist_library
    end
  end

  def self.checklist_wishlist = 'wishlist'

  def self.checklist_library = 'library'

  def total_games = games.count

  def playable_count
    games.select { |game| game.tier == 'native' || game.tier == 'platinum' || game.tier == 'gold' }.length
  end

  def percentage_of_playables
    ((playable_count.to_f * 100) / total_games).round(2).truncate(2)
  end

  Game.tiers.each do |key, _value|
    define_method :"#{key}_count" do
      games.select { |game| game.tier == key }.length
    end

    define_method :"percentage_of_#{key.pluralize}" do
      count = send("#{key}_count")
      ((count.to_f * 100) / total_games).round(2).truncate(2)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/steam_library_controller.rb
# frozen_string_literal: true

# rubocop:disable Style/Documentation
class SteamLibraryController < ApplicationController
  before_action :set_locale
  def index
    @steam_library = SteamLibrary.new
  end

  def show
    @steam_library = SteamLibrary.new(steam_library_params)
    if @steam_library.valid?
      @steam_library.games = load_service
      @steam_library_presenter = SteamLibraryPresenter.new(@steam_library)
      redirect_to steam_library_error_path if zero_game_count?
    else
      show_error_message_and_change_page(I18n.t('steam_library.errors.invalid_value'), steam_library_path)
    end
  rescue MyLibraryOnLinuxError::Error::ResquestError
    show_error_message_and_change_page(I18n.t('steam_library.errors.an_error_occurred'), steam_library_path)
  end

  private

  def steam_library_params
    params.require(:steam_library).permit(:steam_id, :checklist).to_unsafe_hash
  end

  def load_service
    if @steam_library.checklist.eql?(SteamLibrary.checklist_wishlist)
      SteamLibraryService::ShowWishListService.new.call(@steam_library)
    else
      SteamLibraryService::ShowLibraryService.new.call(@steam_library)
    end
  end

  def zero_game_count? = @steam_library.total_games.zero?

  def show_error_message_and_change_page(msg, page)
    flash[:danger] = msg
    redirect_to page
  end

  def set_locale
    session[:locale] = params[:locale] if params[:locale].present?
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    %i[success warning danger].map { |type| alert_box(type) }.join.html_safe
  end

  def alert_box(type)
    "<div class='text-center'>
      <span class='text-#{type}'>#{flash[type]}</span>
    </div>"
  end
end

app/helpers/steam_library_helper.rb
module SteamLibraryHelper
  def row_color(tier)
    case tier
    when 'native'
      'native'
    when 'platinum'
      'platinum'
    when 'gold'
      'gold'
    when 'silver'
      'silver'
    when 'bronze'
      'bronze'
    when 'borked'
      'borked'
    else
      'unknown'
    end
  end

  def trending(game)
    if game.numeric_trending_tier_value > game.numeric_tier_value
      'fa-solid fa-arrow-trend-down'
    elsif game.numeric_trending_tier_value < game.numeric_tier_value
      'fa-solid fa-arrow-trend-up'
    else
      ''
    end
  end

  def games_pie_chart(games)
    colors = { 'native' => '#4da338', 'platinum' => 'rgb(180, 199, 220)', 'gold' => '#ffce41',
               'silver' => 'rgb(166, 166, 166)', 'bronze' => 'rgb(205, 127, 50)', 'borked' => '#bf5151',
               'unknown' => 'rgb(187, 179, 179)' }
    ordered_game = ordered_game(games)
    pie_chart(ordered_game,
              width: '100%',
              height: '100%',
              legend: false,
              donut: true,
              colors: ordered_game.map { |key, _value| colors[key] })
  end

  private

  def ordered_game(games)
    games.sort_by(&:numeric_tier_value)
         .group_by(&:tier)
         .map { |key, value| [key, value.size] }
  end
end

app/views/layouts/_footer.html.erb
<div class="footer text-center">
    <div>
        <span class="text-secondary"><%= t('static_pages.footer.dev', href: link_to("Mário Adriano", "https://br.linkedin.com/in/m%C3%A1rio-s%C3%A9rgio-adriano-5b0bb197", target: "_blank")).html_safe %></span>
    </div>
    <div>
        <span class="text-secondary"><%= t('static_pages.footer.website_is_not_affiliated')%></span>
    </div>        
    <div>
        <a href="https://github.com/mario-adriano/my_library_on_linux">GitHub</a>
        <span class="text-secondary"> | <%= t('static_pages.footer.gpl_license') %> | <%= t('static_pages.footer.version') %> <%= MyLibraryOnLinux::Application::VERSION %></span>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="row header-height">
    <div class="col-sm-3">
        <% unless current_page?(steam_library_path) || current_page?(root_path) %>
            <%= link_to image_tag("mlol.png"), steam_library_path %> <span class="logo-text"><%= t('static_pages.website_name') %></span>
        <% end %>
    </div>
    <% if current_page?(steam_library_path) || current_page?(root_path) %>
        <div class="col-sm-5">
            <div class="right-align">
                <a href="<%= request.path %>?locale=en">
                    <span class="flag-icon flag-icon-us"></span>
                </a>
                <a href="<%= request.path %>?locale=pt-BR">
                    <span class="flag-icon flag-icon-br"></span>
                </a>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyLibraryOnLinux</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('mlol.png') %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/steam_library/_pie_chart.html.erb
<div class="container" align="center">
    <table class="table w-auto small">
        <tbody>
        <tr>
            <td rowspan='8' class='pie-chart-mobile'><div class='pie-chart'><%= games_pie_chart(@steam_library_presenter.games) %></div></td>
            <td>
                <i class="fa-solid fa-circle native"></i> + <i class="fa-solid fa-circle platinum"></i> + <i class="fa-solid fa-circle gold"></i> 
                <span class="playable-pie-chart"><%= t("static_pages.show.playables")%>: </span>
                <%= @steam_library_presenter.playable_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.playable_count) %> 
                (<%= @steam_library_presenter.percentage_of_playables_with_character %>)
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa-solid fa-circle native"></i> 
                <span class="native-pie-chart"><%= t("static_pages.show.tier.native") %>: </span>
                <%= @steam_library_presenter.native_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.native_count) %> 
                (<%= @steam_library_presenter.percentage_of_natives_with_character %>)
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa-solid fa-circle platinum"></i>
                <span class="platinum-pie-chart"><%= t("static_pages.show.tier.platinum") %>: </span>
                <%= @steam_library_presenter.platinum_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.platinum_count) %> 
                (<%= @steam_library_presenter.percentage_of_platinums_with_character %>)
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa-solid fa-circle gold"></i> 
                <span class="gold-pie-chart"><%= t("static_pages.show.tier.gold") %>: </span>
                <%= @steam_library_presenter.gold_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.gold_count) %> 
                (<%= @steam_library_presenter.percentage_of_golds_with_character %>)
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa-solid fa-circle silver"></i> 
                <span class="silver-pie-chart"><%= t("static_pages.show.tier.silver") %>: </span>
                <%= @steam_library_presenter.silver_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.silver_count) %> 
                (<%= @steam_library_presenter.percentage_of_silvers_with_character %>)
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa-solid fa-circle bronze"></i> 
                <span class="bronze-pie-chart"><%= t("static_pages.show.tier.bronze") %>: </span>
                <%= @steam_library_presenter.bronze_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.bronze_count) %> 
                (<%= @steam_library_presenter.percentage_of_bronzes_with_character %>)
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa-solid fa-circle borked"></i> 
                <span class="borked-pie-chart"><%= t("static_pages.show.tier.borked") %>: </span>
                <%= @steam_library_presenter.borked_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.borked_count) %> 
                (<%= @steam_library_presenter.percentage_of_borkeds_with_character %>)
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa-solid fa-circle unknown"></i> 
                <span class="unknown-pie-chart"><%= t("static_pages.show.tier.unknown") %>: </span>
                <%= @steam_library_presenter.unknown_count %> <%= @steam_library_presenter.game_or_games(@steam_library_presenter.unknown_count) %> 
                (<%= @steam_library_presenter.percentage_of_unknowns_with_character %>)
            </td>
        </tr>
        </tbody>
    </table>
</div>

app/views/steam_library/error.html.erb
<div class="container-fluid">
  <div class="light-well box height-vh white-body ">
    <div class="div-error">
      <p class="padding"><%= t('static_pages.error.failed') %></p>
      <div class="div-margin">
        <p><%= t('static_pages.error.change_privacy', href: link_to("link", "https://steamcommunity.com/my/edit/settings", target: "_blank")).html_safe %></p>
        <%= image_tag "steamcommunity/steam-details.#{t('static_pages.error.locale')}.png" %>
      </div> 
    </div> 
  </div>
</div>

app/views/steam_library/index.html.erb
<div class="container-fluid container-margin-top">
  <div class="light-well box height-vh ">
    <div class="row">
      <h1 class="page-header text-center"><%= t('static_pages.website_name') %></h1>
      <p class="light-gray text-center"><%= t('static_pages.index.check')%></p>
    </div>
    <div class="col-sm-12">
      <%= form_with model: @steam_library, method: :get, url: steam_library_show_path, local: true do |f| %>
        <%= hidden_field_tag "steam_library[checklist]", "#{SteamLibrary.checklist_library}" %>
        <div class="row">
          <div class="col-sm-5"></div>
          <div class="col-sm-2">
            <div class="form-group">
              <%= f.text_field :steam_id, autofocus: true, placeholder: "SteamID", class: "form-control", style: "height:45px" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-5"></div>
          <div class="col-sm-2">
            <div class="form-group">
              <%= f.button t('static_pages.index.submit'), class:"form-control btn col-sm-12 btn-success btn-lg btn-block btn", data: 
                    { disable_with: "<i class='fas fa-spinner fa-spin'></i> #{t('static_pages.index.loading')}"} %>
            </div>
            <div class="login-error">
              <%= flash_messages %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/steam_library/show.html.erb
<div class="white-body">
  <%= render "pie_chart" %>
  <%= link_to @steam_library_presenter.list_link_name, steam_library_show_path(:steam_library =>
        {steam_id: @steam_library_presenter.steam_id, checklist: @steam_library_presenter.change_list}), class: "btn btn-primary btn-lg list-link", data: 
                    { disable_with: "<i class='fas fa-spinner fa-spin'></i> #{t('static_pages.index.loading')}"} %>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th><%= t("static_pages.show.table.title") %></th>
        <th><%= t("static_pages.show.table.status") %></th>
      </tr>
    <thead>
    <tbody>
      <% @steam_library_presenter.games.each do |game| %>
        <tr class="<%= game.tier %>">
          <td><%= link_to game.name, game.protondb_url, target: "_blank", class: "protondb_link" %></td>
          <td><%= t("static_pages.show.tier.#{game.tier}") %>  <i class="<%= trending(game) %>"></i></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>